Repository transcom/circleci-docker, pull requests merged in 2023-02, with the labels that each got.

#364 [MB-14914] Upgrade node.js to latest 18.x version (18.13.0)
  .github/PULL_REQUEST_TEMPLATE.md
  .node-version
  README.md
  milmove-app/Dockerfile
  scripts/brew-upgrade
Labels: dependencies, ttv

#348 [ spike ] Updating docs to reflect removing milmove-app-browsers
  README.md
Labels: documentation, enhancement, good first issue, help wanted

#367 [MB-15041, MB-15155] Updating deprecated docker repository reference and base image version
  Dockerfile
Labels: dependencies, infra, ttv

#347 [ spike ] Adding the pre-commit CirlceCI task
  .pre-commit-config.yaml
Labels: enhancement, good first issue, help wanted

#349 [ spike, MB-14548, MB-13732 ] Refactor the release script
  .circleci/config.yml
  release
Labels: enhancement, help wanted, ready-to-merge
